spring:
  application:
    name: websocket-kopring
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
            client-name: Google
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_SECRET_KEY}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - name
              - gender
              - birthday
              - birthyear
          naver:
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_SECRET_KEY}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/chat_socket
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

cipher:
  seed: ${CIPHER_SEED}
redis:
  host: 127.0.0.1
  port: 6379
  timeout: # ms
    connection: 3000
    command: 3000
    shutdown: 1000
oci:
  namespace: ${OCI_NAMESPACE}
  region: ap-chuncheon-1
  bucket: chat-socket